# Generated by Django 3.1.2 on 2020-12-29 15:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(default='cover_pics/default.jpg', upload_to='cover_pics'),
        ),
    ]
