# Generated by Django 3.1.2 on 2021-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210110_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_7',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=130, null=True),
        ),
    ]
