# Generated by Django 4.1.5 on 2023-02-12 13:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to='project_pics'),
        ),
    ]
