# Generated by Django 4.1.5 on 2023-02-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_status',
            field=models.CharField(blank=True, choices=[('open', 'Open to Work'), ('employed', 'Employed'), ('student', 'Student'), ('freelance', 'Freelance'), ('unemployed', 'Unemployed')], max_length=20, null=True),
        ),
    ]
