# Generated by Django 4.1.5 on 2023-02-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
