# Generated by Django 3.1.2 on 2021-01-05 09:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.CharField(default='explore to find more about my capabilities', max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='explore')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('budget', models.CharField(blank=True, help_text='eg, 15-35 USD', max_length=10, null=True)),
                ('jobscategory', models.CharField(choices=[('graphics-design', 'Graphics & Design'), ('Photography', 'Photography'), ('Photoshop', 'Photoshop'), ('Architecture Services', 'Architecture Services'), ('Marketing, Sales and Service', 'Marketing, Sales and Service'), ('Data Entry', 'Data Entry'), ('Web Development and Designing', 'Web Development and Designing'), ('Teaching and Tutoring', 'Teaching and Tutoring'), ('Creative Design', 'Creative Design'), ('Mobile App Development', 'Mobile App Development'), ('3D Modeling and CAD', '3D Modeling and CAD'), ('Game Development', 'Game Development'), ('Translation', 'Translation'), ('Transcription', 'Transcription'), ('Article and Blog Writing', 'Article and Blog Writing'), ('Logo Design and illustration', 'Logo Design and illustration'), ('Audio and Video Production', 'Audio and Video Production')], default='O', max_length=50)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='job_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('budget', models.CharField(blank=True, help_text='eg, 30 USD in 30 days', max_length=25, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
    ]
