# Generated by Django 3.1.2 on 2021-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='overview',
            field=models.TextField(),
        ),
    ]
