# Generated by Django 3.1.2 on 2020-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='view_count',
        ),
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, Budget: 15-35 USD', max_length=10, null=True),
        ),
    ]
