# Generated by Django 3.1.2 on 2021-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210109_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='job',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
