# Generated by Django 3.1.2 on 2020-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, 30 USD in 30 days', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, 15-35 USD', max_length=10, null=True),
        ),
    ]
