# Generated by Django 3.1.2 on 2020-12-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201230_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, 30 USD in 30 days', max_length=25, null=True),
        ),
    ]
