# Generated by Django 4.1.5 on 2023-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_id_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, 15-35 USD', max_length=20, null=True),
        ),
    ]
