# Generated by Django 4.1.5 on 2023-02-13 15:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='project_pics'),
            preserve_default=False,
        ),
    ]
