# Generated by Django 4.1.5 on 2023-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_company_description_remove_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(to='jobs.requirement'),
        ),
    ]
