# Generated by Django 4.2.6 on 2023-12-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(blank=True, help_text='eg, 15-35 USD', max_length=100, null=True),
        ),
    ]
