# Generated by Django 3.1.2 on 2021-01-05 09:02

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('date_contacted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(default='explore to find more about my capabilities', max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('graphics-design', 'Graphics & Design'), ('Photography', 'Photography'), ('Photoshop', 'Photoshop'), ('Architecture-Services', 'Architecture Services'), ('Marketing-Sales-and-Service', 'Marketing, Sales and Service'), ('Data-Entry', 'Data Entry'), ('Web-Development-and-Designing', 'Web Development and Designing'), ('Teaching-and-Tutoring', 'Teaching and Tutoring'), ('Creative-Design', 'Creative Design'), ('Mobile-App-Development', 'Mobile App Development'), ('3D-Modeling-and-CAD', '3D Modeling and CAD'), ('Game-Development', 'Game Development'), ('Translation', 'Translation'), ('Transcription', 'Transcription'), ('Article-and-Blog-Writing', 'Article and Blog Writing'), ('Logo-Design-and-illustration', 'Logo Design and illustration'), ('Audio-and-Video-Production', 'Audio and Video Production')], default='O', max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('last_rating', models.IntegerField(default=0)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='2.jpg', upload_to='post_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All projects',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
