# Generated by Django 4.2.6 on 2023-12-31 14:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
