# Generated by Django 4.2.6 on 2024-01-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_main_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscription_required',
            field=models.BooleanField(default=False),
        ),
    ]
