# Generated by Django 3.1.2 on 2020-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201228_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('graphics-design', 'Graphics & Design'), ('Photography', 'Photography'), ('Photoshop', 'Photoshop'), ('Architecture-Services', 'Architecture Services'), ('Marketing-Sales-and-Service', 'Marketing, Sales and Service'), ('Data-Entry', 'Data Entry'), ('Web-Development-and-Designing', 'Web Development and Designing'), ('Teaching-and-Tutoring', 'Teaching and Tutoring'), ('Creative-Design', 'Creative Design'), ('Mobile-App-Development', 'Mobile App Development'), ('3D-Modeling-and-CAD', '3D Modeling and CAD'), ('Game-Development', 'Game Development'), ('Translation', 'Translation'), ('Transcription', 'Transcription'), ('Article-and-Blog-Writing', 'Article and Blog Writing'), ('Logo-Design-and-illustration', 'Logo Design and illustration'), ('Audio-and-Video-Production', 'Audio and Video Production')], default='O', max_length=50),
        ),
    ]
