# Generated by Django 4.1.5 on 2023-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=1, height_field=300, upload_to='project_pics', width_field=300),
            preserve_default=False,
        ),
    ]
