# Generated by Django 4.1.5 on 2023-02-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_cover_image_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
