# Generated by Django 4.1.5 on 2023-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
