# Generated by Django 4.2.6 on 2023-12-30 16:50

import core.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_remove_post_category_alter_post_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category name', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Enter your message', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='Select categories for this post', to='core.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='project_pics', validators=[core.models.Post.validate_image]),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(help_text='Select a post to comment on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.CharField(help_text='Enter your comment', max_length=300),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='post',
            field=models.ForeignKey(help_text='Select a post to review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.post'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Select a rating'),
        ),
    ]
