# Generated by Django 3.1.2 on 2021-01-07 09:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
